#!/usr/bin/env bash

cp /autograder/submission/* /autograder/source/
cd /autograder/source

[ -f setup.sh ] && chmod +x setup.sh && ./setup.sh

chmod +x ps2

python3 grader.py > ../results/results.json
