#!/usr/bin/env bash

cp /autograder/submission/* /autograder/source/
cd /autograder/source

chmod +x ps1

./ps1 < test-inputs.json > submission_outputs.json

python3 grade.py test-inputs.json test-expected.json submission_outputs.json  > /autograder/results/results.json

